### PR TITLE
fix(router): handle navigating to the empty string in a child router

### LINKED ISSUE #99: navigating to default route in child router navigates to default route in parent
possible router bug?  i have a child router who's first route is "".  the child router belongs to a non-default route in the app router.  when i try to navigate the child router to its default route, the app navigates to the default route in the app router

```javascript
this.router.navigate("", true);
```

### PR DESCRIPTION
**Pull request by bryanrsmith**
fixes #99

### CODE REVIEW

File: src/router.js [hunk 1]
```diff
@@ -84,10 +84,6 @@ export class Router {
       return this.parent.navigate(fragment, options);
     }
 
-    if (fragment === '') {
```
Comment (bryanrsmith) [inline src/router.js]: This case is now handled by `createRootedPath`.
