### PR TITLE
fix(router): properly handle async router configurations

### LINKED ISSUE #213: Multiple viewports cause duplicate routes
I'm trying to setup multiple viewports with Aurelia (http://aurelia.io/docs.html#rendering-multiple-view-ports). However, when I setup the router config to tell which ```<router-view>``` which module to load, the result is that now, ```router.navigation``` has an additional entry for each viewport added.  

For example (modified from the skeleton project):
``` javascript
configureRouter(config, router) {
        config.map([
      { route: ['','welcome'],  name: 'welcome',      viewPorts: {test: {moduleId: 'welcome'}, 		test2: {moduleId: 'welcome'}},      nav: true, title:'Welcome' },
      { route: 'users',         name: 'users',        viewPorts: {test: {moduleId: 'users'}, 		test2: {moduleId: 'users'}},        nav: true, title:'Github Users' }
    ]);
        this.router = router;
}
```
``` html
<div class="page-host">
    <router-view name="test"></router-view>
    
    <router-view name="test2"></router-view>
  </div>
```

The result is now ```router.navigation``` contains duplicate navigations (one duplicate for each router-view)
screen shot 2015-09-18 at 9 52 27 am
screen shot 2015-09-18 at 9 53 33 am

Any ideas on this one? Could it be bad configuration? Or is it something wrong with the router?...

### PR DESCRIPTION
**Pull request by bryanrsmith**
This change moves handling of async router config callbacks into Router.configure to resolve a race condition when using multiple viewPorts. Async configuration was previously handled externally in app-router and route-loading, but that code failed to block subsequent calls from configuring multiple times. Router.configure() now handles async callbacks, setting isConfigured immeditely to allow callers to check state.

BREAKING CHANGES:
  * Router.configure() now always returns a Promise, and is no longer chainable.
  * Router.configure() now applies the configuration in a Promise continuation, so it is not safe to assume that the router will be configured synchronously when the configuration callback is synchronous.

fixes #213

### CODE REVIEW

File: src/app-router.js [hunk 1]
```diff
@@ -85,21 +84,19 @@ export class AppRouter extends Router {
...
+      } else {
+        this.activate();
       }
-
-      this.activate();
     } else {
       this.dequeueInstruction();
     }
+
+    return Promise.resolve();
```
Comment (bryanrsmith) [inline src/app-router.js]: This method now always returns a `Promise`.

File: src/router.js [hunk 2]
```diff
@@ -91,23 +91,22 @@ export class Router {
...
+      config = new RouterConfiguration();
+      result = callbackOrConfig(config);
     }
 
-    this.isConfigured = true;
-    this._resolveConfiguredPromise();
-
-    return this;
+    return Promise.resolve(result).then((c) => {
+      (c || config).exportToRouter(this);
```
Comment (bryanrsmith) [inline src/router.js]: A side effect of this refactor is that the configuration callback may return a new `RouterConfiguration`, if it wants.

File: test/router.spec.js [hunk 3]
```diff
@@ -66,172 +66,166 @@ describe('the router', () => {
   });
 
   describe('generate', () => {
-    it('should generate route URIs', () => {
+    it('should generate route URIs', (done) => {
```
Comment (bryanrsmith) [inline test/router.spec.js]: There are two new tests. All other changes to tests are just moving assertions into `Promise` continuations to handle the new async `Router.configure` implementation.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Sounds good. Feel free to merge it in and continue on :) Thanks!

**Comment by AStoker** [comment]
Any update on when this will be included in the release? There are a few projects on hold (talked on the Aurelia Gitter) for the next release with it's bug fixes.
