### PR TITLE
fix(router): a route with path '/' breaks handleUnknownRoutes

### LINKED ISSUE #116: Possible bug with config.mapUnknownRoutes
one small change,
just change the first route in skeleton-navigation from
```
 { route: ['','welcome'],  moduleId: './welcome',      nav: true, title:'Welcome' },
```
to
```
{ route: ['/','welcome'],  moduleId: './welcome',      nav: true, title:'Welcome' },
```

and `config.mapUnknownRoutes` won't work

### PR DESCRIPTION
**Pull request by bryanrsmith**
Strip leading slash from route paths before registering child handlers to avoid adding bad route paths to child recognizers.

fixes #116

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
This appears to break child routers. Run the skeleton-navigation app and it won't work when clicking on any of the child route nav links.

File: src/router.js [hunk 1]
```diff
@@ -175,14 +175,20 @@ export class Router {
...
+
+    let state = this.recognizer.add({path: path, handler: config});
+
+    if (path) {
       let withChild, settings = config.settings;
       delete config.settings;
       withChild = JSON.parse(JSON.stringify(config));
       config.settings = settings;
-      withChild.route += '/*childRoute';
+      withChild.route = '${path}/*childRoute';
```
Comment (bryanrsmith) [inline src/router.js]: Doh-- wrong quotes. Fix incoming.

**Comment by bryanrsmith** [comment]
I'm not sure how I missed that while testing; sorry. Should be fixed now.

I think I'm going to concentrate on increasing test coverage a bit before tackling more open issues.

**Comment by EisenbergEffect** [comment]
Sounds good :)

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you rebase this on master? Thanks!

**Comment by bryanrsmith** [comment]
@EisenbergEffect Looks like it's up to date now.

**Comment by EisenbergEffect** [comment]
Odd...I had a merge conflict before...but not now. Must have been something strange with my repo at the time.
