### PR TITLE
fix: Prevent running CanDeactivatePreviousStep twice in same navigation

### LINKED ISSUE #45: canDeactivate() is triggered twice
canDeactivate() is triggered twice when you navigate to another route where canActivate returns  new Redirect('...').

Is there any workaround?

### PR DESCRIPTION
**Pull request by davismj**
To handle this, I've added a new parameter to the router called `couldDeactivate` which is set to true whenever the CanDeactivatePreviousStep completes and is reset on every navigation. If a redirect is returned from the CanActivateNextStep, then this value will be true and it is used to build a special pipeline that skips the CanDeactivatePreviousStep on the next pipeline run.

fixes #45

### CODE REVIEW

File: src/activation.js [hunk 1]
```diff
@@ -49,6 +49,8 @@ function processDeactivatable(navigationInstruction: NavigationInstruction, call
       }
     }
 
+    navigationInstruction.router.couldDeactivate = true;
```
Comment (bigopon) [inline src/activation.js]: This will treat `canDeactivate` and `deactivate` the same way. Does that have any implications ?

Comment (davismj) [reply src/activation.js]: No. I originally had a check for `canDeactivate` but it served no purpose and because of the naming of the variable `ignoreResult` I found that the coded was less readable. 

```
if (!ignoreResult) {
  navigationInstruction.router.couldDeactivate = true;
}
```

That's just gunna cause someone to waste 30 minutes figuring out what `ignoreResult` is and why it has anything to do with `couldDeactivate`.
